function q_sol = solveIK(p_des, z_des, q0)

lb = -pi*ones(7,1);
ub =  pi*ones(7,1);

options = optimoptions('fmincon',...
    'Algorithm','sqp',...
    'Display','iter',...
    'MaxIterations',1000,...
    'TolFun',1e-10);

q_sol = fmincon(@(q) ik_cost(q,p_des,z_des),...
                q0,[],[],[],[],lb,ub,[],options);
end